spring:
  application:
    name: spring-ai-api
  ai:
    options:
      model: "deepseek-r1:7b"
    ollama:
      base-url: http://localhost:11434/
      chat:
        enabled: true
    openai:
      chat:
        enabled: false
