spring:
  application:
    name: spring-ai-api
  ai:
    options:
      model: "deepseek-chat"
    openai:
      #api-key: ${OPEN_AI_API_KEY}
      api-key: ${DEEP_SEEK_API_KEY}
      base-url: https://api.deepseek.com/
      chat:
          #model: "gpt-4o"
        enabled: true
    ollama:
      chat:
        enabled: false